/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorAbstracto;
import ec.ups.edu.controlador.ControladorJuez;
import ec.ups.edu.controlador.ControladorPersona;
import ec.ups.edu.controlador.ControladorUsuario;
import ec.ups.edu.modelo.Persona;
import javax.swing.JMenuItem;

/**
 *
 * @author santi
 */
public class VistaPrincipal extends javax.swing.JFrame {

    
    
    ControladorPersona controladorPersona;
    ControladorUsuario controladorUsuario;
    ControladorJuez controladorJuez;
    VentanaRegistroConyugues ventanaRegistro;
    VentanaUsuario ventanaUsuario;
    VentanaJuez ventanaJuez;
    
    public VistaPrincipal() {
        initComponents();
        
        controladorPersona =controladorPersona.getInstance();
        controladorUsuario = controladorUsuario.getInstance();
        controladorJuez = controladorJuez.getInstance();
        ventanaRegistro = new VentanaRegistroConyugues(controladorPersona);
        ventanaUsuario = new VentanaUsuario(controladorUsuario,this);
        ventanaJuez = new VentanaJuez(controladorJuez);
        
        itemRegistrarConyugue.setVisible(false);
        itemRegistroJuez.setVisible(false);
        itemRegistroTestigos.setVisible(false);
        itemRegistroMatrimonio.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemRegistrarConyugue = new javax.swing.JMenuItem();
        itemIniciarSesion = new javax.swing.JMenuItem();
        itemRegistroTestigos = new javax.swing.JMenuItem();
        itemRegistroJuez = new javax.swing.JMenuItem();
        itemRegistroMatrimonio = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Inicio");

        itemRegistrarConyugue.setMnemonic('o');
        itemRegistrarConyugue.setText("Registro Conyugues");
        itemRegistrarConyugue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarConyugueActionPerformed(evt);
            }
        });
        fileMenu.add(itemRegistrarConyugue);

        itemIniciarSesion.setMnemonic('s');
        itemIniciarSesion.setText("Iniciar Sesion");
        itemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(itemIniciarSesion);

        itemRegistroTestigos.setMnemonic('a');
        itemRegistroTestigos.setText("Registro testigos");
        fileMenu.add(itemRegistroTestigos);

        itemRegistroJuez.setMnemonic('a');
        itemRegistroJuez.setText("Registro Juez");
        itemRegistroJuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistroJuezActionPerformed(evt);
            }
        });
        fileMenu.add(itemRegistroJuez);

        itemRegistroMatrimonio.setMnemonic('a');
        itemRegistroMatrimonio.setText("Registro matrimonio");
        fileMenu.add(itemRegistroMatrimonio);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        fileMenu.add(itemSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemRegistrarConyugueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarConyugueActionPerformed
        
        desktopPane.add(ventanaRegistro);
        ventanaRegistro.setVisible(true);
        
    }//GEN-LAST:event_itemRegistrarConyugueActionPerformed

    private void itemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionActionPerformed
        
        desktopPane.add(ventanaUsuario);
        ventanaUsuario.setVisible(true);
        
    }//GEN-LAST:event_itemIniciarSesionActionPerformed

    private void itemRegistroJuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistroJuezActionPerformed
        
        desktopPane.add(ventanaJuez);
        ventanaJuez.setVisible(true);
        
    }//GEN-LAST:event_itemRegistroJuezActionPerformed

    
    
    
    public JMenuItem itemConyugue(){
        
        return itemRegistrarConyugue;
        
    }
    public JMenuItem itemMatrimonio(){
        
        return itemRegistroMatrimonio;
        
    }
    
    public JMenuItem itemRegistrarJuez(){
        
        return itemRegistroJuez;
        
    }
    
    public JMenuItem itemTestigos(){
        
        return itemRegistroJuez;
        
    }
            
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem itemIniciarSesion;
    private javax.swing.JMenuItem itemRegistrarConyugue;
    private javax.swing.JMenuItem itemRegistroJuez;
    private javax.swing.JMenuItem itemRegistroMatrimonio;
    private javax.swing.JMenuItem itemRegistroTestigos;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
